- name: install cutadapt
  pip: name=cutadapt 
       version={{ cutadapt_version }}
       virtualenv={{ biopet_dir }}/programs/cutadapt/

- file: src={{ biopet_dir }}/programs/cutadapt/bin/cutadapt dest={{ biopet_dir }}/bin/cutadapt state=link

- set_fact: cutadapt_exe={{ biopet_dir }}/bin/cutadapt
