- name: Download picard package
  get_url: url=https://github.com/broadinstitute/picard/releases/download/{{ picard_version }}/picard-tools-{{ picard_version }}.zip
           dest=/tmp/picard.{{ picard_version }}.zip
  register: picard_download

- file: path={{ biopet_dir }}/programs/picard/{{ picard_version }} state=directory mode=755

- name: Extracting picard
  unarchive: >
    copy=no
    src=/tmp/picard.{{ picard_version }}.zip
    dest={{ biopet_dir }}/programs/picard/{{ picard_version }}
  when: picard_download|changed

- set_fact: picard_jar={{ biopet_dir }}/programs/picard/{{ picard_version }}/picard-tools-{{ picard_version }}/picard.jar
