---
- hosts: all
  remote_user: root
  become_user: root
  roles:
  - role: git
  - role: java7-oracle
  - role: maven3
  - role: gatk-protected
  - role: biopet
  vars:
    biopet_dir: /usr/local/biopet
    biopet_version: develop
    biopet_python2_env: "{{ biopet_dir }}/python_envs/pyhton2"
    biopet_python3_env: "{{ biopet_dir }}/python_envs/pyhton3"
    maven_version: 3.3.3
    maven_url: http://www.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
    maven_dir: "{{ biopet_dir }}/programs/maven/apache-maven-{{ maven_version }}"

