---
- hosts: all
  remote_user: root
  become_user: root
  become: true
  roles:
  - role: biopet
  - role: references
  vars:
    biopet_dir: /usr/local/biopet
    biopet_version: develop
    reference_dir: /usr/local/biopet/references
  handlers:
    - name: Create config from template
      template: src=templates/biopet_config.yml.j2 dest={{ biopet_config }} mode=644
