---
- hosts: all
  remote_user: root
  become_user: root
  roles:
  - role: java7-oracle
  - role: maven3
  - role: gatk-protected
  vars:
    biopet_dir: /usr/local/biopet
    maven_version: 3.3.3
    maven_url: http://www.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
    maven_dir: "{{ biopet_dir }}/apache-maven-{{ maven_version }}"

