---

- file: path={{ reference_dir }}/{{ species }}/{{ reference_name }}/annotation state=directory mode=755

- name: Download reference
  get_url: url={{ reference_url }}
           dest={{ reference_dir }}/{{ species }}/{{ reference_name }}/reference.fasta

- name: Create fai
  command: >
    {{ samtools_exe }} faidx {{ reference_dir }}/{{ species }}/{{ reference_name }}/reference.fasta
  when: samtools_exe is defined

- file: path={{ reference_dir }}/{{ species }}/{{ reference_name }}/reference.dict state=absent
  become: true

- name: Create dict
  command: java -cp {{ picard_jar }} picard.sam.CreateSequenceDictionary
           "REFERENCE={{ reference_dir }}/{{ species }}/{{ reference_name }}/reference.fasta"
           "OUTPUT={{ reference_dir }}/{{ species }}/{{ reference_name }}/reference.dict"
  when: biopet_jar is defined

- block:
  - file: path={{ reference_dir }}/{{ species }}/{{ reference_name }}/bwa state=directory mode=755
  - file: src={{ reference_dir }}/{{ species }}/{{ reference_name }}/reference.fasta
          dest={{ reference_dir }}/{{ species }}/{{ reference_name }}/bwa/reference.fasta
          state=link
  - command: >
      {{ bwa_exe }} index {{ reference_dir }}/{{ species }}/{{ reference_name }}/bwa/reference.fasta
      chdir="{{ reference_dir }}/{{ species }}/{{ reference_name }}/bwa"
  when: bwa_exe is defined

- block:
  - file: path={{ reference_dir }}/{{ species }}/{{ reference_name }}/star state=directory mode=755
  - file: src={{ reference_dir }}/{{ species }}/{{ reference_name }}/reference.fasta
          dest={{ reference_dir }}/{{ species }}/{{ reference_name }}/star/reference.fasta
          state=link
  # Need to add gtf file here
  - command: >
      {{ star_exe }}
      --runThreadN {{ threads|default(1) }}
      --runMode genomeGenerate
      --genomeDir {{ reference_dir }}/{{ species }}/{{ reference_name }}/star
      --genomeFastaFiles {{ reference_dir }}/{{ species }}/{{ reference_name }}/star/reference.fasta
      chdir="{{ reference_dir }}/{{ species }}/{{ reference_name }}/star"
  when: star_exe is defined
