bcftools_version: "1.3"
bedtools_version: "v2.25.0"
bowtie_version: "v1.1.2"
bowtie2_version: "v2.2.7"
bwa_version: "0.7.12"
cufflinks_version: "2.2.1"
cutadapt_version: "1.9"
fastqc_version: "0.11.2"
freebayes_version: "v1.0.2"
gatk_version: "3.5"
htseq_version: "0.6.1"
htslib_version: "1.3"
picard_version: "1.141"
samtools_version: "1.3"
seqtk_version: "4feb6e81444ab6bc44139dd3a125068f81ae4ad8"
sickle_version: "v1.33"
star_version: "2.5.1b"
varscan_version: "v2.4.1"
vt_version: "0.57"
vep_version: 83

maven_version: "3.3.3"
maven_url: http://www.apache.org/dist/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz
maven_dir: "{{ biopet_dir }}/programs/maven/apache-maven-{{ maven_version }}"

biopet_version: feature-sample_selector
biopet_dir: /usr/local/biopet
