---
- command: echo $PWD

- get_url: url={{ maven_url }} dest=/tmp/maven.{{ maven_version }}.tgz

- get_url: url={{ maven_url }}.md5 dest=/tmp/maven.{{ maven_version }}.md5

- command: echo " "{{ maven_url }} >> /tmp/maven.{{ maven_version }}.md5 && md5sum -c /tmp/maven.{{ maven_version }}.md5

- file: path={{ biopet_dir }}/programs/maven state=directory
  become: true

- unarchive: >
    copy=no
    src=/tmp/maven.{{ maven_version }}.tgz
    dest={{ biopet_dir }}/programs/maven/
  become: true

#- file: path=/tmp/maven.tgz state=absent

#- file: path=/tmp/maven.md5 state=absent

- file: src={{ maven_dir }}/bin/mvn dest=/usr/local/bin/mvn owner=root group=root state=link
  become: true

