---

- git: repo=https://git.lumc.nl/biopet/biopet.git
       dest={{ biopet_dir }}/src/biopet
       version={{ biopet_version }}
       force=yes
  register: biopet_checkout
  become: true
  name: Checkout biopet on {{ biopet_version }}

- command: chdir={{ biopet_dir }}/src/biopet
           mvn -DskipTests=true clean install
  when: biopet_checkout.before != biopet_checkout.after
  become: true
  name: Build biopet

- file: path={{ biopet_dir }}/programs/biopet/ state=directory
  become: true
  name: checking biopet dir

- name: Check config dir
  file: path={{ biopet_dir }}/config/ state=directory
  become: true

- name: Check bin dir
  file: path={{ biopet_dir }}/bin/ state=directory
  become: true

- find: paths={{ biopet_dir }}/src/biopet/protected/biopet-protected-package/target/ patterns="Biopet-?.?.?*.jar"
  register: find_jar
  name: Finding final jar

- set_fact: biopet_jar={{ biopet_dir }}/programs/biopet/{{ find_jar.files[0].path|basename }}
- set_fact: biopet_config={{ biopet_dir }}/config/biopet.{{ biopet_version }}.yml

- copy: src={{ find_jar.files[0].path }} dest={{ biopet_jar }} mode=644 remote_src=yes
  become: true
  name: Copy jar

- template: src=templates/biopet_profile.sh.j2 dest=/etc/profile.d/biopet.sh mode=755
  become: true
  name: Setting up biopet profile
