- name: Clone bwa git repo
  git: repo=https://github.com/lh3/bwa.git
       dest={{ biopet_dir }}/src/bwa
       version={{ version }}
       force=yes

- name: Compiling bwa
  command: make
           chdir={{ biopet_dir }}/src/bwa

- file: path={{ biopet_dir }}/programs/bwa
        state=directory
        mode=755

- name: Copy binary
  copy: src={{ biopet_dir }}/src/bwa/bwa
        dest={{ biopet_dir }}/programs/bwa/bwa-{{ version }}
        remote_src=yes
        mode=755

- file: src={{ biopet_dir }}/programs/bwa/bwa-{{ version }}
        dest={{ biopet_dir }}/programs/bwa/bwa
        state=link

- file: src={{ biopet_dir }}/programs/bwa/bwa
        dest={{ biopet_dir }}/bin/bwa
        state=link

- set_fact: bwa_exe={{ biopet_dir }}/programs/bwa/bwa-{{ version }}
