- name: Clone freebayes git repo
  git: repo=https://github.com/ekg/freebayes.git
       dest={{ biopet_dir }}/src/freebayes
       version={{ freebayes_version }}
       force=yes
  register: freebayes_checkout

- name: Compiling freebayes
  command: make
           chdir={{ biopet_dir }}/src/freebayes
  when: freebayes_checkout.before != freebayes_checkout.after

- name: Installing freebayes
  command: make prefix={{ biopet_dir }} install
           chdir={{ biopet_dir }}/src/freebayes
  when: freebayes_checkout.before != freebayes_checkout.after

- set_fact: freebayes_exe={{ biopet_dir }}/bin/freebayes
