---

- name: Checkout biopet on {{ biopet_version }}
  git: repo=https://git.lumc.nl/biopet/biopet.git
       dest={{ biopet_dir }}/src/biopet
       version={{ biopet_version }}
       force=yes
  register: biopet_checkout

- name: Build biopet
  command: chdir={{ biopet_dir }}/src/biopet
           {{ maven_exe }} -DskipTests=true clean install
  when: biopet_checkout.before != biopet_checkout.after

- name: checking biopet dir
  file: path={{ biopet_dir }}/programs/biopet/ state=directory

- name: Check config dir
  file: path={{ biopet_dir }}/config/ state=directory
  become: true

- name: Check bin dir
  file: path={{ biopet_dir }}/bin/ state=directory

- name: Finding final jar
  find: paths={{ biopet_dir }}/src/biopet/protected/biopet-protected-package/target/ patterns="Biopet-?.?.?*.jar"
  register: find_jar

- set_fact: biopet_jar={{ biopet_dir }}/programs/biopet/{{ find_jar.files[0].path|basename }}
- set_fact: biopet_config={{ biopet_dir }}/config/biopet.{{ biopet_version }}.yml

- name: Copy jar
  copy: src={{ find_jar.files[0].path }} dest={{ biopet_jar }} mode=644 remote_src=yes

- name: Create config from template
  template: src=templates/biopet_config.yml.j2 dest={{ biopet_config }} mode=644

- template: src=templates/biopet_reference_config.yml.j2 dest={{ biopet_dir }}/config/{{ item.species }}_{{ item.name }}.yml mode=644
  with_items: "{{ references }}"

- set_fact: biopet_profile_configs="{{ biopet_profile_configs }} + ['{{ biopet_dir }}/config/{{ item.species }}_{{ item.name }}.yml']"
  with_items: "{{ references }}"

- name: Write biopet profile
  template: src=templates/biopet_profile.sh.j2 dest=/etc/profile.d/biopet.sh mode=755
