---

- include: java7-oracle.yml
- include: maven3.yml version=3.3.3
- include: ubuntu-packages.yml
- include: htslib.yml version=1.3

# Flexiprep

- include: fastqc.yml version=0.11.2
- include: seqtk.yml version=4feb6e81444ab6bc44139dd3a125068f81ae4ad8
- include: sickle.yml version=v1.33
- include: cutadapt.yml version=1.9

# Mapping

- include: picard.yml version=1.141
- include: bwa.yml version=0.7.12
- include: star.yml version=2.5.1b
- include: bowtie.yml version=v1.1.2
- include: samtools.yml version=1.3
- include: bedtools.yml version=v2.25.0

# Shiva

- include: gatk-protected.yml version=3.5
- include: bcftools.yml version=1.3
- include: vt.yml version=0.57
- include: freebayes.yml version=v1.0.2
- include: varscan.yml version=v2.4.1

# Gentrap

- include: htseq.yml version=0.6.1
- include: cufflinks.yml version=2.2.1

# Biopet

- include: biopet.yml
